<?php

// SESSION-START ====================================================================================================

	session_start();
	
	if( isset($_COOKIE['remember']) ) {
		header('Location: termsbackend.php');
		exit;
	}
?>

<!-- HTML =========================================================================================================== -->

<!DOCTYPE html>
<html lang="de">

	<head>
		<meta charset="UTF-8">
		<title>Terms & Privacy</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="expires" content="0">
		<link rel="stylesheet" type="text/css" href="src/css/styles.css">
		<link rel="stylesheet" type="text/css" href="src/fontawesome/css/all.css">
		<link href="https://fonts.googleapis.com/css?family=Lato|Raleway&display=swap" rel="stylesheet">
		<script src="src/js/javascript.js"></script>
	</head>
	
	<body>
	
<!-- INCLUDING: MODAL + TOP-NAVIGATION + REGISTER/LOGIN/FORGOT FORMS ================================================ -->

		<?php require('src/includes/forms.php'); ?>
		
		<br>
		
<!-- MAIN PRIVACY-POLICY ============================================================================================ -->	
		
		<main class="main">

			<h2>Privacy Policy</h2>
			<p>Your privacy is important to us.<br>
			It is Privat's policy to respect your privacy regarding any information we may collect from you across our website,<br>
			<a href="https://klehmann.000webhostapp.com/">https://klehmann.000webhostapp.com/</a>, and other sites we own and operate.</p>

			<p>We only ask for personal information when we truly need it to provide a service to you.<br>
			We collect it by fair and lawful means, with your knowledge and consent.<br>
			We also let you know why we’re collecting it and how it will be used.</p>

			<p>We only retain collected information for as long as necessary to provide you with your requested service.<br>
			What data we store, we’ll protect within commercially acceptable means to prevent loss and theft,<br>
			as well as unauthorised access, disclosure, copying, use or modification.</p>

			<p>We don’t share any personally identifying information publicly or with third-parties, except when required to by law.</p>

			<p>Our website may link to external sites that are not operated by us.<br>
			Please be aware that we have no control over the content and practices of these sites,<br>
			and cannot accept responsibility or liability for their respective privacy policies.</p>

			<p>You are free to refuse our request for your personal information,<br>
			with the understanding that we may be unable to provide you with some of your desired services.</p>

			<p>Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information.<br>
			If you have any questions about how we handle user data and personal information, feel free to contact us.</p>

			<p>This policy is effective as of 6 December 2019.</p>

			<p>Generated by <a title="Privacy Policy Template Generator" href="https://getterms.io/">GetTerms.io</a></p>

		</main>
		
<!-- FOOTER-NAVIGATION ============================================================================================== -->

		<footer id="footernav">
			<ul>			
				<li>
					<a href="legal.php" title="Legal" id="legal"
					   class="">Legal</a>
				</li>
				<li>
					<a href="contact.php" title="Contact" id="contact"
					   class="">Contact</a>
				</li>
				<li>
					<a href="terms.php" title="terms" id="terms"
					   class="active">Terms & Privacy</a>
				</li>
			</ul>
		</footer>
		
<!-- INCLUDE: PHP+JS FORMS-ERRORMESSAGE ============================================================================= -->		

		<?php require('src/includes/forms-error.php'); ?>
		
	</body>
</html>